In [69]:
import numpy as np
np.random.seed(4)
A=np.random.randint(1,100,50)
A

array([47, 56, 70,  2, 88, 73, 51, 10, 59, 95, 56, 56, 58, 37, 51, 45, 39,
       53,  4,  1, 56, 22, 22, 74, 39, 57, 67, 47, 31,  9, 50, 67, 59, 88,
       33, 41, 43, 46, 34, 33, 29,  4, 80, 99, 96, 58, 51, 18, 82, 90])

In [70]:
np.sort(A)

array([ 1,  2,  4,  4,  9, 10, 18, 22, 22, 29, 31, 33, 33, 34, 37, 39, 39,
       41, 43, 45, 46, 47, 47, 50, 51, 51, 51, 53, 56, 56, 56, 56, 57, 58,
       58, 59, 59, 67, 67, 70, 73, 74, 80, 82, 88, 88, 90, 95, 96, 99])

In [72]:
for i in range(len(A)-1):
    pick = i
    for j in range(i+1,len(A)):
        if A[pick]>A[j]:
            pick =j
    A[i],A[pick] = A[pick],A[i]
print(A)
        
        
        

[ 1  2  4  4  9 10 18 22 22 29 31 33 33 34 37 39 39 41 43 45 46 47 47 50
 51 51 51 53 56 56 56 56 57 58 58 59 59 67 67 70 73 74 80 82 88 88 90 95
 96 99]


In [79]:
def Insertion_sort(array):
    for i in range(len(array)-1):
        pick = i
        for j in range(i+1,len(array)):
            if array[pick]>array[j]:
                pick =j
        array[i],array[pick] = array[pick],array[i]
    print(array)

In [80]:
B = np.random.randint(1,200,40)
B

array([160,  36, 159,  66, 132,  87, 120,  75, 149,   8, 180,  11,  42,
       144,  42,   4,  75,  99, 152, 103,   8, 106,  53, 157, 116, 193,
       166,  33,  26,  38,   6,  75, 153,  30,  37, 190,   3, 148,  23,
        29])

In [81]:
np.sort(B)

array([  3,   4,   6,   8,   8,  11,  23,  26,  29,  30,  33,  36,  37,
        38,  42,  42,  53,  66,  75,  75,  75,  87,  99, 103, 106, 116,
       120, 132, 144, 148, 149, 152, 153, 157, 159, 160, 166, 180, 190,
       193])

In [82]:
Insertion_sort(B)

[  3   4   6   8   8  11  23  26  29  30  33  36  37  38  42  42  53  66
  75  75  75  87  99 103 106 116 120 132 144 148 149 152 153 157 159 160
 166 180 190 193]
